name: Update Holidays

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  download:
    name: download and check changes
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.filter.outputs.changed }}

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: download latest csv
        run: ./scripts/update_holidays.sh

      - name: check changes
        id: filter
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  commit:
    name: commit and release
    needs: download
    if: ${{ needs.download.outputs.changed == 'true' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: download latest csv
        run: ./scripts/update_holidays.sh

      - name: get new version
        id: get_new_version
        run: |
          RESULT=$(./scripts/get_new_version.sh)
          echo "version=${RESULT}" >> "$GITHUB_OUTPUT"

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "v${{ steps.get_new_version.outputs.version }}"

      - name: tag
        run: |
          git tag ${{ steps.get_new_version.outputs.version }}
          git push origin ${{ steps.get_new_version.outputs.version }}

      - name: release
        uses: softprops/action-gh-release@v3
        with:
          name: v${{ steps.get_new_version.outputs.version }}
          tag_name: ${{ steps.get_new_version.outputs.version }}
